# Generated by Django 5.2.4 on 2025-09-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام خاصیت')),
            ],
            options={
                'verbose_name': 'خاصیت',
                'verbose_name_plural': 'خواص',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='products', to='home.property', verbose_name='خواص محصول'),
        ),
    ]
