# Generated by Django 5.2.4 on 2025-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پیگیری پرداخت'),
        ),
    ]
